name: mechapp
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences:
  cupertino_icons: ^0.1.2

  image_picker: #TODO configure for iOS later
  google_maps_flutter: ^0.5.24+1 #TODO configure for iOS later
  firebase_database:
  intent: ^1.1.0
  firebase_core: ^0.4.0+9
  firebase_auth: ^0.14.0+5
  cloud_firestore: ^0.13.4+2
  url_launcher:
  cached_network_image:
  rave_flutter: ^0.0.9-alpha+1 #TODO configure the iOS version later
  geolocator: ^5.3.0 #TODO configure the iOS version later
  geocoder: ^0.2.1
  provider:
  intl: ^0.16.1
  smooth_star_rating:

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Raleway
      fonts:
        - asset: assets/fonts/raleway.ttf
